#!/usr/bin/env bash
#Script to install Upload to Imgur nautilus-script

echo "Creating directories..."
gksudo mkdir /usr/share/uploadtoimgur/

echo "Copying files..."
cp Upload\ to\ Imgur ~/.local/share/nautilus/scripts/
gksudo cp uploader.py /usr/share/uploadtoimgur/

echo "Setting permissions"
chmod u+x ~/.local/share/nautilus/scripts/Upload\ to\ Imgur
gksudo chmod a+x /usr/share/uploadtoimgur/uploader.py

echo "Done!"
