#!/usr/bin/env bash
#Script to uninstall Upload to Imgur nautilus-script

echo "Removing files"
gksudo "rm -rf /usr/share/uploadtoimgur/"
rm ~/.local/share/nautilus/scripts/Upload\ to\ Imgur

echo "Done!"
